
server:
  servlet:
    context-path: /mtom-server

  port: 8443
  ssl:
    protocol: TLSv1.2
    key-store-type: PKCS12
    key-store: data/mykeystore.p12
    key-store-password: password
    key-alias: mykeypair

logging:
  level:
    org.springframework.ws: DEBUG
