spring:
  application:
    name: demo-application
  
  main:
    banner-mode: log
#    web-application-type: none

  lifecycle:
    timeout-per-shutdown-phase: 10s
  
  messages:
    basename: messages
    encoding: UTF-8

  datasource:
    # PostgreSQL JDBC Driver: https://github.com/pgjdbc/pgjdbc
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo
    #url: jdbc:postgresql://192.168.1.100:5432/todo
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      data-source-properties:
        #loginTimeout: 0
        connectTimeout: 10
        socketTimeout: 0

  transaction:
    default-timeout: 10s
#
#  sql:
#    init:
#      schema-locations:
#      - xxx
#      data-locations:
#      - xxx

server:
  port: 8080
#  servlet:
#    context-path: /hoge
  shutdown: graceful
  tomcat:
    threads:
      max: 30
      min-spare: 5
#    basedir: target/work/tomcat
#  error:
#    include-binding-errors: false
#    include-exception: false
#    include-stacktrace: never
#
#management:
#
              
logging:
#  config: classpath:logback.xml
  level:
    root: INFO
    '[com.example]': DEBUG
    '[com.zaxxer.hikari]': DEBUG

B_prop1: test

demo:
  prop1: d1
  prop2: d2

